"""
Caribou - Module Creator
Checks installed software, creates modulefiles, shows module avail table.
"""

import os
import shutil
import subprocess

MODULES_BASE = "/home/kaveripk/modules"
CARIBOU_DIR  = os.path.join(MODULES_BASE, "caribou")

# ── Software registry ─────────────────────────────────────────────────────── #
SOFTWARE = {
    "python3": {
        "binary":     "python3",
        "binary_path": "/usr/bin/python3",
        "lib_path":   "/usr/lib/python3",
        "version_cmd": ["python3", "--version"],
        "module_dir": "python3",
        "module_name": "system",
    },
    "gcc": {
        "binary":     "gcc",
        "binary_path": "/usr/bin/gcc",
        "lib_path":   "/usr/lib/gcc",
        "version_cmd": ["gcc", "--version"],
        "module_dir": "gcc",
        "module_name": "system",
    },
    "intel": {
        "binary":     "icx",
        "binary_path": "/opt/intel/oneapi/compiler/latest/bin/icx",
        "lib_path":   "/opt/intel/oneapi/compiler/latest/lib",
        "version_cmd": ["icx", "--version"],
        "module_dir": "intel",
        "module_name": "oneapi",
    },
    "aocc": {
        "binary":     "clang",
        "binary_path": "/home/kaveripk/aocc-compiler-4.2.0/bin/clang",
        "lib_path":   "/home/kaveripk/aocc-compiler-4.2.0/lib",
        "version_cmd": ["/home/kaveripk/aocc-compiler-4.2.0/bin/clang", "--version"],
        "module_dir": "aocc",
        "module_name": "4.2",
    },
    "openmpi": {
        "binary":     "mpirun",
        "binary_path": "/usr/bin/mpirun",
        "lib_path":   "/usr/lib/x86_64-linux-gnu",
        "version_cmd": ["mpirun", "--version"],
        "module_dir": "openmpi",
        "module_name": "system",
    },
}


# ── Helpers ───────────────────────────────────────────────────────────────── #

def _get_version(cmd):
    try:
        out = subprocess.check_output(cmd, stderr=subprocess.STDOUT, text=True)
        return out.splitlines()[0].strip()
    except Exception:
        return "unknown"


def _is_installed(binary_path):
    return os.path.isfile(binary_path) and os.access(binary_path, os.X_OK)


def _write_modulefile(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


# ── Check all software ────────────────────────────────────────────────────── #

def check_all():
    """
    Check which software is installed.
    Returns dict: { name: { installed, version, path } }
    """
    status = {}
    for name, cfg in SOFTWARE.items():
        installed = _is_installed(cfg["binary_path"])
        version   = _get_version(cfg["version_cmd"]) if installed else "not found"
        status[name] = {
            "installed": installed,
            "version":   version,
            "path":      cfg["binary_path"],
        }
    return status


# ── Create modulefiles ────────────────────────────────────────────────────── #

def create_modulefile(name):
    """Create a modulefile for a given software name."""
    cfg = SOFTWARE.get(name)
    if not cfg:
        print(f"[module] unknown software: {name}")
        return None

    if not _is_installed(cfg["binary_path"]):
        print(f"[module] ✘ {name} not installed — skipping modulefile")
        return None

    binary_dir = os.path.dirname(cfg["binary_path"])
    lib_path   = cfg["lib_path"]
    mod_path   = os.path.join(MODULES_BASE, cfg["module_dir"], cfg["module_name"])

    # skip if modulefile already exists
    if os.path.isfile(mod_path):
        print(f"[module] ✔ modulefile already exists : {mod_path}")
        return mod_path

    content = f"""#%Module1.0
# Auto-generated by Caribou
# Software : {name}
# Binary   : {cfg['binary_path']}

proc ModulesHelp {{}} {{
    puts stderr "{name} - auto-generated by Caribou"
    puts stderr "Binary: {cfg['binary_path']}"
}}

module-whatis "{name}"

prepend-path PATH            {binary_dir}
prepend-path LD_LIBRARY_PATH {lib_path}
"""
    _write_modulefile(mod_path, content)
    print(f"[module] ✔ modulefile created : {mod_path}")
    return mod_path


def create_all_modulefiles():
    """Create modulefiles for all installed software."""
    print("\n[module] Creating modulefiles for all installed software ...")
    for name in SOFTWARE:
        create_modulefile(name)


# ── Create caribou benchmark modulefiles ─────────────────────────────────── #

def create_stream_module(binary_path):
    """Create modulefile for STREAM benchmark."""
    binary_dir  = os.path.dirname(os.path.abspath(binary_path))
    module_path = os.path.join(CARIBOU_DIR, "stream")
    os.makedirs(CARIBOU_DIR, exist_ok=True)

    content = f"""#%Module1.0
# Auto-generated by Caribou
# Benchmark : STREAM (memory bandwidth)
# Binary    : {binary_path}

proc ModulesHelp {{}} {{
    puts stderr "STREAM memory bandwidth benchmark"
    puts stderr "Binary: {binary_path}"
}}

module-whatis "STREAM memory bandwidth benchmark"

prepend-path PATH            {binary_dir}
prepend-path LD_LIBRARY_PATH {binary_dir}

setenv STREAM_BINARY {binary_path}
"""
    _write_modulefile(module_path, content)
    print(f"[module] ✔ modulefile created : {module_path}")
    print(f"[module]   usage              : module load caribou/stream")
    return module_path


def create_hpl_module(binary_path, compiler):
    """Create modulefile for HPL benchmark."""
    binary_dir  = os.path.dirname(os.path.abspath(binary_path))
    module_name = f"hpl-{compiler}"
    module_path = os.path.join(CARIBOU_DIR, module_name)
    os.makedirs(CARIBOU_DIR, exist_ok=True)

    content = f"""#%Module1.0
# Auto-generated by Caribou
# Benchmark : HPL ({compiler.upper()})
# Binary    : {binary_path}

proc ModulesHelp {{}} {{
    puts stderr "HPL benchmark compiled with {compiler.upper()}"
    puts stderr "Binary: {binary_path}"
}}

module-whatis "HPL benchmark ({compiler.upper()})"

prepend-path PATH            {binary_dir}
prepend-path LD_LIBRARY_PATH {binary_dir}

setenv HPL_BINARY   {binary_path}
setenv HPL_COMPILER {compiler.upper()}
"""
    _write_modulefile(module_path, content)
    print(f"[module] ✔ modulefile created : {module_path}")
    print(f"[module]   usage              : module load caribou/{module_name}")
    return module_path


# ── Show module avail table ───────────────────────────────────────────────── #

def show_module_avail():
    """
    Show a table like `module avail` for all software
    including caribou benchmarks.
    """
    status = check_all()

    print(f"\n{'='*60}")
    print(f"  Module Availability (Caribou)")
    print(f"{'='*60}")
    print(f"  {'Module':<25} {'Status':<15} {'Version'}")
    print(f"  {'─'*55}")

    # system software
    for name, cfg in SOFTWARE.items():
        s        = status[name]
        mod_dir  = SOFTWARE[name]["module_dir"]
        mod_name = SOFTWARE[name]["module_name"]
        full_mod = f"{mod_dir}/{mod_name}"
        marker   = "✔" if s["installed"] else "✘"
        ver      = s["version"][:35] if s["installed"] else "not installed"
        print(f"  {marker} {full_mod:<23} {'installed' if s['installed'] else 'missing':<15} {ver}")

    # caribou benchmarks
    print(f"  {'─'*55}")
    for bname in ["stream", "hpl-intel", "hpl-aocc"]:
        mod_path = os.path.join(CARIBOU_DIR, bname)
        exists   = os.path.isfile(mod_path)
        marker   = "✔" if exists else "✘"
        status_s = "available" if exists else "not built"
        print(f"  {marker} {'caribou/' + bname:<23} {status_s:<15}")

    print(f"{'='*60}\n")


# ── Main (run standalone) ─────────────────────────────────────────────────── #

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(
        description="Caribou Module Creator"
    )
    parser.add_argument("--check",       action="store_true", help="check all software")
    parser.add_argument("--create-all",  action="store_true", help="create all modulefiles")
    parser.add_argument("--avail",       action="store_true", help="show module avail table")
    parser.add_argument("--create",      type=str,            help="create modulefile for specific software")
    args = parser.parse_args()

    if args.check:
        status = check_all()
        print(f"\n  {'Software':<15} {'Installed':<12} {'Path'}")
        print(f"  {'─'*55}")
        for name, s in status.items():
            mark = "✔" if s["installed"] else "✘"
            print(f"  {mark} {name:<13} {str(s['installed']):<12} {s['path']}")
        print()

    elif args.create_all:
        create_all_modulefiles()
        show_module_avail()

    elif args.avail:
        show_module_avail()

    elif args.create:
        create_modulefile(args.create)

    else:
        parser.print_help()
